# Generated by Django 4.1.2 on 2022-11-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_category',
            new_name='is_deleted',
        ),
    ]
