# Generated by Django 4.1.2 on 2022-11-17 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_comapny_remove_user_logo_user_role_product_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold_by',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_by',
            field=models.ManyToManyField(to='ecommerce.merchantfirm'),
        ),
    ]
