# Generated by Django 4.1.2 on 2022-11-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_merchantfirm_product_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.ManyToManyField(related_name='products', to='ecommerce.category'),
        ),
    ]
